package com.luto

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable

/**
 * Created by furqan on 12/07/2017.
 */


@DynamoDBTable(tableName = "Bio")
class Bio (

    @DynamoDBHashKey
    var Name: String,

    @DynamoDBAttribute
    var Branch: String,

    @DynamoDBAttribute
    var Mobile: String,

    @DynamoDBAttribute
    var Residence: String
) {
    override fun equals(o: Any?): Boolean {
        if (o == null || o !is Bio) return false
        return Name == o.Name
    }

    override fun hashCode(): Int {
        return Name.hashCode()
    }
}